### ISSUE TITLE
Switch local storage to use Resonite package system

### ISSUE THREAD

**Issue by epicEaston197** [art0007i/LocalStorage#6]
The way the items are saved currently makes it so that cloud assets stay as cloud assets and local assets stay as local assets which is not very preferable for long term storage I would rather if the mod use the package system

an alternative is just to use the file browser and make a folder in inventory like paths that's what I've been doing

**Comment by art0007i** [comment]
I won't do this. best I can do is ensure all assets are local assets and none are linked to the cloud when you save but I'm not sure if youd want to use it then. 

Saving each asset as package is super inefficient for disk space

**Comment by epicEaston197** [comment]
> Saving each asset as package is super inefficient for disk space

but isn't this the whole point of why people download the mod?

**Comment by art0007i** [comment]
to waste 10x as much disk than they could be if it saved all assets locally? I hope not

**Comment by ihateratelimitssomuch** [comment]
Doesn’t this make assets unreliable? ~~If it’s lost from the cloud~~ if you clear your cache there’s no way to save it from it’s fate.

**Comment by epicEaston197** [comment]
> Doesn’t this make assets unreliable? ~If it’s lost from the cloud~ if you clear your cache there’s no way to save it from it’s fate.

This goes for local assets as well If you clear your cache they're deleted

**Comment by art0007i** [comment]
Local assets only get cleared if you delete the "Assets" folder located next to your local db. Clearing the cache has no effect. But like I think it's not a bad idea to have a local storage fork called package storage which would do what you want. I just have no interest in having that mod, or making it myself
